# Generated by Django 2.2.7 on 2019-11-13 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='account_reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massagetype', models.CharField(choices=[('N', 'NUAT THAI FOOT MASSAGE (1 HOUR) P350.00'), ('T', 'THAI BODY MASSAGE (1 HOUR) P350.00'), ('S', 'SWEDISH MASSAGE (1 HOUR) P400.00'), ('A', 'AROMATHERAPY MASSAGE (1 HOUR) P400.00'), ('E', 'EXPRESS - BACK AND HEAD (30 MINS) P250.00'), ('F', 'FOOT MASSAGE (30 HOUR) P250.00'), ('B', 'BACK MASSAGE (30 HOUR) P250.00'), ('H', 'HEAD MASSAGE (30 HOUR) P250.00')], max_length=1)),
                ('therapist', models.CharField(choices=[('F', 'FEMALE'), ('M', 'MALE')], max_length=1)),
                ('mobile_number', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('specialinstruction', models.TextField(blank=True)),
                ('reference_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
